server:
  port: 8762

eureka:
  instance:
    hostname: eureka-server2 #主机名
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka #eureka服务端地址
    register-with-eureka: true #是否将自己的路径注册到 eureka上。 eureka server不需要，eureka consumer client 需要
    fetch-registry: true # 是否需要从eureka上面抓取路径。 eureka server不需要，eureka consumer client 需要

spring:
  application:
    name: eureka-server-ha # 给注册的应用取名字