server:
  port: 8761

eureka:
  instance:
    hostname: localhost #主机名
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #eureka服务端地址
    register-with-eureka: true
    fetch-registry: true
