server:
  port: 8000

eureka:
  instance:
    hostname: localhost #主机名
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #eureka服务端地址


spring:
  application:
    name: eureka_provider