server:
  port: 9000

eureka:
  instance:
    hostname: localhost #主机名
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://eureka-server1:8761/eureka,http://eureka-server2:8762/eureka #eureka服务端地址
# eureka 应用名称
spring:
  application:
    name: eureka_consumer

  #日志记录
logging:
  level:
    cn: debug
  #开启降级方式，默认是关闭
feign:
  hystrix:
    enabled: true
